[project]
name = "mts-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "oluckygal", email = "104176652+oluckygal@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
mts-data = "mts_data:main"

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.0",
]
